import "./assets/main.css";
import "@formkit/themes/genesis";
import { plugin, defaultConfig } from "@formkit/vue";
import config from "../formkit.config";
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import "./index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import { createPinia } from "pinia";
const app = createApp(App);
const pinia = createPinia();
app.use(router);
app.use(plugin, defaultConfig(config));
app.use(pinia);
app.mount("#app");
